# Generated by Django 3.0.6 on 2020-05-25 19:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200524_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 5, 25, 19, 50, 23, 790977, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
